### ISSUE TITLE
NullPointerException Crash

### ISSUE THREAD

**Issue by s1lenced7** [OreCruncher/Environs#1]
Attempted to add mod to modded minecraft instance, received :
> java.lang.NullPointerException: Unexpected error 

Crash.log
[crash-2020-02-03_20.02.16-client.txt](https://github.com/OreCruncher/Environs/files/4149663/crash-2020-02-03_20.02.16-client.txt)

Debug.log
[debug.log](https://github.com/OreCruncher/Environs/files/4149671/debug.log)

**Comment by OreCruncher** [comment]
Several questions:

1. Is this pack available online?
2. Does it always happen, or do you run around for a bit then it occurs?

**Comment by s1lenced7** [comment]
1. Is this pack available online?
 - Mod Selection of my own making.

2. Does it always happen, or do you run around for a bit then it occurs?
- Minecraft can launch properly, crashes upon entering world.

Since this is not related to an Official ModPack i'd treat this as low-prio if you've got any other issues. i'm willing to provide more details if needed. (eg. a zip of the mods if you want to debug locally)

**Comment by OreCruncher** [comment]
I don't think that is needed.  I believe I know what the problem is.  Question is how it came to be.  It looks like blocks were registered after the block registration phase of mod startup.  I am making some code changes based on that.  Would you be willing to take a private build and test?

**Comment by s1lenced7** [comment]
Sure thing, let me know how to proceed and when.

EDIT:
A bit late but found out that generating a "default world" without biomes o' plenty does not crash and works as expected

**Comment by OreCruncher** [comment]
I actually develop with BoP (and Serene Seasons) installed, so I don't think it is BoP.  Find a one off build here: https://github.com/OreCruncher/Environs/releases/tag/0.0.6.0-Test

**Comment by s1lenced7** [comment]
Issue looks to be resolved with the changes made, was able to play for over an hour without crashing.
I've got another unrelated thing I've noticed about rain ripples and droplet effects during rain.
I'll open a separate issue for that if you'd like.

**Comment by OreCruncher** [comment]
Yes please. :)  I had to make some significant changes to how that worked for 1.14.4.

**Comment by s1lenced7** [comment]
Turns out the issue was not related to Environs mod.  *Phew*
Only thing i'd mention is to check the scaling on the lava-spouts, they seem rather large at points.

Thank you for all the time you put in!!! <3

**Comment by OreCruncher** [comment]
There should be a max scale size.  The size of the flame indicates how deep the lava is.  Calculation is capped at 10 blocks.

**Comment by OreCruncher** [comment]
Pushed release build 0.1.0.0 to CurseForge
