### ISSUE TITLE
Crash Nullpointerror

### ISSUE THREAD

**Issue by EternalOne11** [OreCruncher/Environs#8]
I keep getting a crash with another mod but I can't find out even with others peoples help on the modded Minecraft discord.
https://paste.dimdev.org/eladotoqaz.rb

**Comment by OreCruncher** [comment]
Update to the release versions of Sound Control, Environs, and Mob Effects.  The issue is that the some blocks were registered after the block registration phase so Environs was not able to process.

**Comment by EternalOne11** [comment]
oh that is a problem anyway to fix it?

**Comment by OreCruncher** [comment]
Yes.  Update to the latest versions of the mods. :)  I put in a work around to handle.

**Comment by EternalOne11** [comment]
oh did not notice I was using an outdated version of the mod.
